// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeatherMonitor.Api.Infrastructure.Persistence;

#nullable disable

namespace WeatherMonitor.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524210155_AddTickerQTables")]
    partial class AddTickerQTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TickerQ.Utilities.Entities.CronTickerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Expression")
                        .HasColumnType("text");

                    b.Property<string>("Function")
                        .HasColumnType("text");

                    b.Property<string>("InitIdentifier")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemPaused")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("Request")
                        .HasColumnType("bytea");

                    b.Property<int>("Retries")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("RetryIntervals")
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Expression")
                        .HasDatabaseName("IX_CronTickers_Expression");

                    b.HasIndex("Function", "Expression")
                        .HasDatabaseName("IX_Function_Expression");

                    b.ToTable("CronTickers", "ticker");
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.CronTickerOccurrenceEntity<TickerQ.Utilities.Entities.CronTickerEntity>", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CronTickerId")
                        .HasColumnType("uuid");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockHolder")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("SkippedReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CronTickerId")
                        .HasDatabaseName("IX_CronTickerOccurrence_CronTickerId");

                    b.HasIndex("ExecutionTime")
                        .HasDatabaseName("IX_CronTickerOccurrence_ExecutionTime");

                    b.HasIndex("CronTickerId", "ExecutionTime")
                        .IsUnique()
                        .HasDatabaseName("UQ_CronTickerId_ExecutionTime");

                    b.HasIndex("Status", "ExecutionTime")
                        .HasDatabaseName("IX_CronTickerOccurrence_Status_ExecutionTime");

                    b.ToTable("CronTickerOccurrences", "ticker");
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.TimeTickerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("ElapsedTime")
                        .HasColumnType("bigint");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExecutionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Function")
                        .HasColumnType("text");

                    b.Property<string>("InitIdentifier")
                        .HasColumnType("text");

                    b.Property<string>("LockHolder")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Request")
                        .HasColumnType("bytea");

                    b.Property<int>("Retries")
                        .HasColumnType("integer");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("RetryIntervals")
                        .HasColumnType("integer[]");

                    b.Property<int?>("RunCondition")
                        .HasColumnType("integer");

                    b.Property<string>("SkippedReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionTime")
                        .HasDatabaseName("IX_TimeTicker_ExecutionTime");

                    b.HasIndex("ParentId");

                    b.HasIndex("Status", "ExecutionTime")
                        .HasDatabaseName("IX_TimeTicker_Status_ExecutionTime");

                    b.ToTable("TimeTickers", "ticker");
                });

            modelBuilder.Entity("WeatherMonitor.Domain.Deliveries.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("JobId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_id");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Payload", "WeatherMonitor.Domain.Deliveries.WebhookDelivery.Payload#DeliveryPayload", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ClientId")
                                .IsRequired()
                                .HasJsonPropertyName("client_id");

                            b1.Property<DateOnly>("ForecastDate")
                                .HasJsonPropertyName("forecast_date");

                            b1.Property<Guid>("MonitorId")
                                .HasJsonPropertyName("monitor_id");

                            b1.Property<string>("TimeZoneId")
                                .IsRequired()
                                .HasJsonPropertyName("time_zone_id");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Location", "WeatherMonitor.Domain.Deliveries.WebhookDelivery.Payload#DeliveryPayload.Location#WeatherLocation", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Code")
                                        .HasJsonPropertyName("code");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasJsonPropertyName("name");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasJsonPropertyName("state");

                                    b2.HasJsonPropertyName("location");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "WeatherCondition", "WeatherMonitor.Domain.Deliveries.WebhookDelivery.Payload#DeliveryPayload.WeatherCondition#WeatherCondition", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasJsonPropertyName("code");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasJsonPropertyName("description");

                                    b2.HasJsonPropertyName("weather_condition");
                                });

                            b1
                                .ToJson("payload")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Status", "ScheduledFor")
                        .HasDatabaseName("ix_webhook_delivery_status_scheduled_for");

                    b.ToTable("webhook_delivery", (string)null);
                });

            modelBuilder.Entity("WeatherMonitor.Domain.Monitors.WeatherMonitorConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_id");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("WeatherCondition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("weather_condition");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "WeatherMonitor.Domain.Monitors.WeatherMonitorConfiguration.Location#MonitorLocation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("CityCode")
                                .HasColumnType("integer")
                                .HasColumnName("monitor_location_city_code");

                            b1.Property<string>("CityName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("monitor_location_city_name");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("monitor_location_state");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Webhook", "WeatherMonitor.Domain.Monitors.WeatherMonitorConfiguration.Webhook#WebhookSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AccessToken")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("webhook_settings_access_token");

                            b1.Property<TimeOnly>("ScheduleFor")
                                .HasColumnType("time without time zone")
                                .HasColumnName("webhook_settings_schedule_for");

                            b1.Property<string>("TimeZoneId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("webhook_settings_time_zone_id");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("webhook_settings_url");
                        });

                    b.HasKey("Id");

                    b.ToTable("weather_monitor_configuration", (string)null);
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.CronTickerOccurrenceEntity<TickerQ.Utilities.Entities.CronTickerEntity>", b =>
                {
                    b.HasOne("TickerQ.Utilities.Entities.CronTickerEntity", "CronTicker")
                        .WithMany()
                        .HasForeignKey("CronTickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CronTicker");
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.TimeTickerEntity", b =>
                {
                    b.HasOne("TickerQ.Utilities.Entities.TimeTickerEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TickerQ.Utilities.Entities.TimeTickerEntity", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
