// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WeatherMonitor.Api.Infrastructure.Persistence;

#nullable disable

namespace WeatherMonitor.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WeatherMonitor.Domain.Deliveries.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("JobId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_id");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Payload", "WeatherMonitor.Domain.Deliveries.WebhookDelivery.Payload#DeliveryPayload", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ClientId")
                                .IsRequired()
                                .HasJsonPropertyName("client_id");

                            b1.Property<DateOnly>("ForecastDate")
                                .HasJsonPropertyName("forecast_date");

                            b1.Property<Guid>("MonitorId")
                                .HasJsonPropertyName("monitor_id");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Location", "WeatherMonitor.Domain.Deliveries.WebhookDelivery.Payload#DeliveryPayload.Location#WeatherLocation", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Code")
                                        .HasJsonPropertyName("code");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasJsonPropertyName("name");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasJsonPropertyName("state");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "WeatherCondition", "WeatherMonitor.Domain.Deliveries.WebhookDelivery.Payload#DeliveryPayload.WeatherCondition#WeatherCondition", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasJsonPropertyName("code");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasJsonPropertyName("description");
                                });

                            b1
                                .ToJson("payload")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Status", "ScheduledFor")
                        .HasDatabaseName("ix_webhook_delivery_status_scheduled_for");

                    b.ToTable("webhook_delivery", (string)null);
                });

            modelBuilder.Entity("WeatherMonitor.Domain.Monitors.WeatherMonitorConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("client_id");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<string>("WeatherCondition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("weather_condition");

                    b.Property<DateTimeOffset>("created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "WeatherMonitor.Domain.Monitors.WeatherMonitorConfiguration.Location#MonitorLocation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("CityCode")
                                .HasColumnType("integer")
                                .HasColumnName("monitor_location_city_code");

                            b1.Property<string>("CityName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("monitor_location_city_name");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("monitor_location_state");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Webhook", "WeatherMonitor.Domain.Monitors.WeatherMonitorConfiguration.Webhook#WebhookSettings", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("AccessToken")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("webhook_settings_access_token");

                            b1.Property<TimeOnly>("ScheduleFor")
                                .HasColumnType("time without time zone")
                                .HasColumnName("webhook_settings_schedule_for");

                            b1.Property<string>("TimeZoneId")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("webhook_settings_time_zone_id");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("webhook_settings_url");
                        });

                    b.HasKey("Id");

                    b.ToTable("weather_monitor_configuration", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
